on:
  push:
    branches: [main]

jobs:
  build:
    name: Build wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node and npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build grammar
        run: |
          npm install --save-dev tree-sitter-cli
          ./node_modules/.bin/tree-sitter generate
          ./node_modules/.bin/tree-sitter build-wasm